version: "3.9"

networks:
  news-minio:
    name: news-minio
    external: true
  news-redis:
    name: news-redis
    external: true

volumes:
  minio-data:
    name: minio-data
    external: false

  redis-data:
    name: redis-data
    external: false

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-01-12T02-06-16Z.fips
    container_name: minio-1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin}
      # MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    command: server --console-address ":9090" /data/minio/
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data/minio/
    networks:
      - news-minio
  
  redis:
    image: redis:7.0.5
    container_name: news-redis-1
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 45s
      interval: 10s
      retries: 10
    command: redis-server --requirepass ${REDIS_PASSWORD:-test}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - news-redis
  
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongouser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopassword
      - ME_CONFIG_MONGODB_URL=mongodb://mongouser:mongopassword@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mongouser
      - ME_CONFIG_BASICAUTH_PASSWORD=mongopassword
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
